//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEGORY
    {
        public CATEGORY()
        {
            this.QUESTIONS = new HashSet<QUESTION>();
        }
    
        public int CATEGORY_ID { get; set; }
        public string CATEGORY_NAME { get; set; }
        public Nullable<int> CATEGORY_FKEY_ADMINID { get; set; }
        public string CATEGORY_ENC_STRING { get; set; }
    
        public virtual ADMIN ADMIN { get; set; }
        public virtual ICollection<QUESTION> QUESTIONS { get; set; }
    }
}
